### ISSUE TITLE
2.4.2 SSID and modules issue

### ISSUE THREAD

**Issue by PaulMoore2018** [d1slact0r/pineapple-firmware-builder#4]
I'm currently running 2.0.2 which hasn't put a foot wrong... literally everything I've tried works perfectly.

However, trying to upgrade to 2.4.2 has been headache and a half!  I've tried building it manually & am now running your 2.4.2 build.

After installing, it shows "2.4.2" as the version number (so it's clearly upgraded), however a recon scan shows non-associated clients but no SSIDs at all, despite being surrounded by them under 2.0.2

Most importantly however, you can't install modules (even ones around 1KB in size) as it complains about a lack of space.

On 2.0.2
Filesystem                Size      Used Available Use% Mounted on
/dev/root                12.5M     12.5M         0 100% /rom
tmpfs                    29.5M     92.0K     29.4M   0% /tmp
/dev/mtdblock5            2.0M    828.0K      1.2M  40% /overlay
overlayfs:/overlay        2.0M    828.0K      1.2M  40% /
tmpfs                   512.0K         0    512.0K   0% /dev

On 2.4.2
Filesystem                Size      Used Available Use% Mounted on
rootfs                  384.0K    232.0K    152.0K  60% /
/dev/root                14.3M     14.3M         0 100% /rom
tmpfs                    29.8M    120.0K     29.7M   0% /tmp
tmpfs                    29.8M     88.0K     29.7M   0% /tmp/root
tmpfs                   512.0K         0    512.0K   0% /dev
/dev/mtdblock5          384.0K    232.0K    152.0K  60% /overlay
overlayfs:/overlay      384.0K    232.0K    152.0K  60% /

I'd appreciate your help.  Thanks!

**Comment by mankidavu** [comment]
One option is to add a USB and try to convert it to extroot.
https://openwrt.org/docs/guide-user/additional-software/extroot_configuration

Other option is to rebuild it with minimal stuff/driver support and release more space for overlay partition.

**Comment by d1slact0r** [comment]
You def need a extra SD card, just like the normal pineapple nano ;) so closing this
more info: https://github.com/d1slact0r/pineapple-firmware-builder/wiki/USB-Storage-(FSTAB)
